### PR TITLE
software/user: split DMA handling into an API

### PR DESCRIPTION
**Pull request by sergachev**
The purpose of this changeset is to provide a clean and simple API to handle DMA reads and writes in user software and examples of it. I know the pull request looks huge, but code is 95% same as before, just reshuffled into different functions/files and deduplicated. It's worth starting looking at it from litepcie_dma_minimal_example.c which should be self-explanatory:
 - create struct litepcie_dma_ctrl
 - init with litepcie_dma_init()
 - run litepcie_dma_process() in a loop
 - use litepcie_dma_next_read_buffer() and litepcie_dma_next_write_buffer() in the same loop to read/write buffers
 - end with litepcie_dma_cleanup()

Zero-copy can now be used seamlessly anywhere by passing a flag to litepcie_dma_init().

Note I was still not able to test litepcie_test record and play properly yet even after setting `pcie_dma0.writer.sink.valid.eq(1), pcie_dma0.reader.source.ready.eq(1)` even before these changes - not sure why.

litepcie_util dma_test seems to work correctly though.

### CODE REVIEW

**Comment by sjkelly** [comment]
I tested this locally on the fairwaves xtrx and both `litepcie_util` and `litepcie_dma_minimal_example` are failing to make DMA transfers in both normal and zero-copy mode.

**Comment by sergachev** [comment]
Thanks for testing!
Does it work before these changes? Do you get any errors in console and dmesg?
I of course tested too (on acorn - https://github.com/sergachev/litepcie_acorn), but will be able to test again only in a week or so.

**Comment by sjkelly** [comment]
>  Does it work before these changes? Do you get any errors in console and dmesg?

Yes, the original userspace seems to work fine. I will keep investigating so I can give a better diagnostic.

**Comment by maleadt** [comment]
I'm not seeing any issues here with an XTRX and this PR, both modes work.

**Pull request merged**
